Various fixes (#54)
* Fix for logbook error: "TypeError: get_context() got an unexpected keyword argument 'parent_context'"

* Fix contributor page translations via synced duplicate mechanism

* Remove unused `content_type_id` method which broke the CMS add child page btn

* Link to users' contributor pages

* Fix the order of fields in the Episode editor page, so audio is up top

* Reuse template for related page thumbnails

* Fix letter spacing of microcopy h4

* Remove Contributor pages uniqueconstraint (commented out code)

* Override letter-spacing from the scss file